# This is an autogenerated function, ported from the original legacy version.
# It /should work/ as is, but will not have all the benefits of the modern
# function API. You should see the function docs to learn how to add function
# signatures for type safety and to document this function using puppet-strings.
#
# https://puppet.com/docs/puppet/latest/custom_functions_ruby.html
#
# ---- original file header ----
# taken from saz/ssh and modified (FW)
# ---- original file header ----
#
# @summary
#   Returns all ip addresses of network interfaces (except lo) found by facter.
#
#
Puppet::Functions.create_function(:'ipaddresses') do
  # @param args
  #   The original array of arguments. Port this to individually managed params
  #   to get the full benefit of the modern function API.
  #
  # @return [Data type]
  #   Describe what the function returns here
  #
  dispatch :default_impl do
    # Call the method named 'default_impl' when this is matched
    # Port this to match individual params for better type safety
    repeated_param 'Any', :args
  end


  def default_impl(*args)
    
        interfaces = lookupvar('interfaces')

        return false if (interfaces == :undefined)

        result = []

        interfaces = interfaces.split(',')
        interfaces.each do |iface|
            if ! iface.include?('lo')
                ipaddr = lookupvar("ipaddress_#{iface}")
                ipaddr6 = lookupvar("ipaddress6_#{iface}")
                if ipaddr
                    result << ipaddr
                end
                if ipaddr6
                    result << ipaddr6
                end
            end
        end

        return result
    
  end
end
